### ISSUE TITLE
OSError: libcublas.so.9.0 -- despite having cuda10.0 installed

### ISSUE THREAD

**Issue by mhusseinsh** [CannyLab/tsne-cuda#72]
Hello
I am trying to run tsnecuda
Here is my following code:
```
import numpy as np
# to measure exec time
from sklearn.manifold import TSNE
from tsnecuda import TSNE as TSNE_CUDA
from timeit import default_timer as timer
import random
#from sklearn.manifold import TSNE
RS = 20150101
  
# normal function to run on cpu 
def func(a):
    X = np.vstack([a])
    tsneData = TSNE(n_components=2, random_state=RS, perplexity=30).fit_transform(a)
  
# function optimized to run on gpu                           
def func2(a): 
    X = np.vstack([a])
    tsneData = TSNE_CUDA(n_components=2, random_seed=RS, perplexity=30).fit_transform(a)

if __name__=="__main__": 

    data = []
    for i in range (11):
        data1 = np.random.randint(low=0, high=255, size=100, dtype=np.uint8)
        data.append(data1)

    start = timer() 
    func(data) 
    print("without GPU:", timer()-start)     
    
    start = timer() 
    func2(data) 
    print("with GPU:", timer()-start) 
```
However I receive an error
```
Traceback (most recent call last):
  File "testGPU.py", line 36, in <module>
    func2(data) 
  File "testGPU.py", line 22, in func2
    tsneData = TSNE_CUDA(n_components=2, random_seed=RS, perplexity=30).fit_transform(a)
  File "/home/user/.local/lib/python2.7/site-packages/tsnecuda/TSNE.py", line 110, in __init__
    self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
  File "/usr/local/lib/python2.7/dist-packages/numpy/ctypeslib.py", line 152, in load_library
    return ctypes.cdll[libpath]
  File "/usr/lib/python2.7/ctypes/__init__.py", line 437, in __getitem__
    return getattr(self, name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 432, in __getattr__
    dll = self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```
It is weird since I already have cuda 10.0
```
cat /usr/local/cuda/version.txt
CUDA Version 10.1.168
```
why does it look for cuda 9.0 then?

**Comment by DavidMChan** [comment]
Thanks for reporting this issue, please follow the following when reporting a bug: https://github.com/CannyLab/tsne-cuda/wiki/Reporting-Bugs 

It seems like you haven't installed the correct version of tsnecuda (cuda 9 version instead of cuda 10 version). Follow the instructions here to install: https://github.com/CannyLab/tsne-cuda/wiki/Installation

**Comment by mhusseinsh** [comment]
@DavidMChan thanks for the info
I installed it via `pip install tsnecuda`, how can i specify the cuda version using pip?

**Comment by DavidMChan** [comment]
We no longer support the pip installation (because of precisely this issue). Please install using conda, or from source.
